log:
    level: info

entryPoints:
    http:
      address: ":80"
    https:
      address: ":443"

# Docker Provider
providers:
    docker:
      endpoint: "unix:///var/run/docker.sock"
      network: "${traefik_network}"
      swarmMode: false
      exposedByDefault: false

# Enable dashboard
api:
    dashboard: true

# Let's Encrypt
certificatesResolvers:
    letsEncrypt:
        acme:
            email: "${acme_email}"
            caServer: ${le_production_url} # Use Let's Encrypt staging server when experimenting to avoid hitting Let's Encrypts rate limit
            storage: ${acme_storage_path}
            keyType: "${lets_encrypt_keytype}"
            httpChallenge:
                # used during the challenge
                entryPoint: http
    letsEncryptStaging:
        acme:
            email: "${acme_email}"
            caServer: ${le_staging_url}
            storage: ${acme_storage_path}
            keyType: "${lets_encrypt_keytype}"
            httpChallenge:
                # used during the challenge
                entryPoint: http
${cf_resolver}

accessLog: {}

metrics:
    prometheus:
        buckets:
        - 0.1
        - 0.3
        - 1.2
        - 5
        manualRouting: true